### ISSUE TITLE
Causes a freeze the pi when choosing  physical pin 4

### ISSUE THREAD

**Issue by juggledad** [bpmurray/node-red-contrib-dht-sensor#14]
If you use this node and choose to use the physical pins and select pin 4 - which is a ground pin (so this probably applies to the other ground pins too) - as soon as you hit 'depoy' the pi will totally freeze and the only way out is a power off/on.

When you choose physical pins, none of the ground or power pins should be allowed to be selected.

You might want to take a look at the GPIO node to see how it selects pins.

**Comment by bpmurray** [comment]
I'll update the doc.

**Comment by juggledad** [comment]
Don't you think you should prevent the selection of the grounding pins?
