### ISSUE TITLE
Not working on Rpi 4 (BCM2711)

### ISSUE THREAD

**Issue by jabberman** [bpmurray/node-red-contrib-dht-sensor#19]
It doesn´t work on my new Pi 4 with BCM2711. Is there a chance to fix?

**Comment by bpmurray** [comment]
I'm afraid "doesn't work" is not particularly helpful: can you give a precise description of the problem, please. What have you tried and what failure do you see?

**Comment by jabberman** [comment]
Sorry, the problem is caused of the Pi4. It has different Chipset to my Pi 3B.
It´s a Python problem, i solved by using this: https://learn.adafruit.com/dht-humidity-sensing-on-raspberry-pi-with-gdocs-logging/python-setup

In console the DHT22 shows me the Humidity, in node red it only shows :  
rpi-dht22 : msg.payload : string[4]
"0.00"

With my old Pi 3B it´s working . The GPIO Pins setup is correct.
