### ISSUE TITLE
installation with node.js 12.7 failed

### ISSUE THREAD

**Issue by nobodyMO** [bpmurray/node-red-contrib-dht-sensor#2]
node-red now supports node.js 12.x. 
But this node will be removed after update of node.js 12.7.
The installation with npm failed. 
Please change the required version to support the installation with node.js 12.7.

146 error Linux 3.18.11-v7+
147 error argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-dht-sensor"
148 error node v0.12.7
149 error npm  v2.11.3
150 error code ELIFECYCLE
151 error node-dht-sensor@0.0.6 install: `node-gyp rebuild`
151 error Exit status

**Comment by nobodyMO** [comment]
As workaround I have copied the node files directly in the nodes directory. 
The node is still working with node.js 12.7.

**Comment by bpmurray** [comment]
I think this has already been addressed. I'll verify that today.

**Comment by bpmurray** [comment]
This has been OK for quite some time.
