### ISSUE TITLE
DHT22 sensors not working on Pi 4B 8GB

### ISSUE THREAD

**Issue by MissingCatPE** [bpmurray/node-red-contrib-dht-sensor#20]
Hi :)

I am struggling to get the DHT22 working on my Pi 4B. If I replicate the exact setup onto my Pi 3B+ it works immediately.

I looked around online and I noted that there are other users experiencing a similar issue with their Pi 4 modules.

The libraries work, as I can access them using python, but I think there is something that needs updating on the node itself. I use this node all the time and would greatly appreciate a look at this and possibly and update.

Regards,

**Comment by MissingCat69** [comment]
Please ignore this issue.

I was using an alternate power supply to power the DHT22 to avoid using the pins on the pi. These needed to share a ground with the pi to make them work.

My test bench had this and my pi 4 did not.
