### ISSUE TITLE
node-dht-sensor doesn't have readSpec function anymore

### ISSUE THREAD

**Issue by mcgurk** [bpmurray/node-red-contrib-dht-sensor#6]
Solution? (worked for me):
~/.node-red/node_modules/node-red-contrib-dht-sensor/dht22-node/dht22-node.js
            //reading = sensorLib.readSpec(this.dht, this.pin);
            reading = sensorLib.read(this.dht, this.pin);

**Comment by aleonnet** [comment]
Great, but now I'm having the error:
bcm2835_init: Unable to open /dev/mem: Permission denied
31 Oct 00:47:46 - [error] [rpi-dht22:f3a6d3dc.e8c0a] TypeError: failed to initialize

Anyone knows how to fix it?
Thanks

**Comment by bpmurray** [comment]
Code updated and deployed to npmjs.org, along with some other minor updates.
