### ISSUE TITLE
RFE - add sensor type to output

### ISSUE THREAD

**Issue by juggledad** [bpmurray/node-red-contrib-dht-sensor#7]
I have a case where I use multiple dhtxx's and ds18b20's. I want to have one subflow to process the data that I get and store both location and the sensor type. Currently this node only passes back the sensor model or the node name. I'd like to see the name (as location), topic and sensor model. 

RFE: pass the node name (as msg.location), the node topic (as msg.topic) and the sensor model (as msg.sensorid). This can be done by editing and changing line 86 from:
         msg.topic    = node.topic || node.name;
to:
         msg.location = node.name;
         msg.topic      = node.topic;
         msg.sensorid   = 'dht' + node.dht;

**Comment by bpmurray** [comment]
I'll keep the current msg.topic setting just in case anyone depends on it, but adding the others is fine.

**Comment by juggledad** [comment]
Awesome, thanks!

**Comment by juggledad** [comment]
You might want to update the readme with the new information

**Comment by bpmurray** [comment]
All updated now.
