### ISSUE TITLE
Node only returns temperature string

### ISSUE THREAD

**Issue by spectralcodec** [bpmurray/node-red-contrib-dht-sensor#8]
Using with DHT-22 on Raspberry Pi 1 and only receiving temperature string (e.g. "23.90")

**Comment by bpmurray** [comment]
This may be a misunderstanding. The temperature is returned in msg.payload, but msg.humidity contains the humidity.

**Comment by spectralcodec** [comment]
That was it, thanks!

**Comment by patricktokeeffe** [comment]
Breaking the payload apart and creating a separate `.humidity` attribute was an unfortunate choice. A JSON payload like `{"T": 23.9, "RH": 56.0}` would have been much easier to work with.

**Comment by bpmurray** [comment]
Ah, but the thing was developed over time along with my ds18b20 node, so it was easier to have the payload be temp and a separate humidity item. In hindsight it clearly was not the best solution, but it is what it is!
